#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

echo "--- Building App ---"
npm run build
if [[ "$?" == 0 ]]; then
    echo "\t\033[32mBuild Passed\033[0m"
else
    echo "\t\033[41mBuild Failed\033[0m"
    exit 1
fi
echo "--- Running ES-Lint ---"
npm run lint
if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed\033[0m"
else
    echo "\t\033[41mESLint Failed\033[0m"
    exit 1
fi
echo "--- Running Unit Tests ---"
npm run test
if [[ "$?" == 0 ]]; then
    echo "\t\033[32mUnit Tests Passed\033[0m"
else
    echo "\t\033[41mUnit Tests Failed\033[0m"
    exit 1
fi