#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

echo "--- Building App ---"
npm run build
echo "--- Running ES-Lint ---"
npm run lint-fix
echo "--- Running Unit Tests ---"
npm run test