/* eslint-disable quotes */
import { Season, ShowData } from '../../types';

const fakeSeason: Season = {
    id: 1,
    name: 'season 1',
    season_number: 1,
    episode_count: 5,
    air_date: 'fake date',
    vote_average: 1,
    poster_path: 'fake poster',
    overview: 'fake season',
};

/**
 * A sample show data array that can be used for unit testing
 * which contains both movies and tv shows
 */
export const SHOW_DATA_ARRAY: ShowData[] = [
    {
        id: 1726,
        poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
        title: 'Iron Man',
        release_date: '2008-04-30',
        runtime: 126,
        vote_average: 7.639,
        vote_count: 24715,
        overview:
            'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
        media_type: 'movie',
        genre_ids: [28, 878, 12],
    },
    {
        id: 169934,
        poster_path: '/eHDez1uN5X2ZAq4niX7HvhyZIIO.jpg',
        title: 'Iron Man: Rise of Technovore',
        release_date: '2013-04-24',
        runtime: 88,
        vote_average: 5.918,
        vote_count: 152,
        overview:
            "Iron Man enlists the help of ruthless vigilante the Punisher to track down War Machine's murderer. All the while, he's being pursued by S.H.I.E.L.D. agents Black Widow and Hawkeye, who suspect his involvement in a recent terrorist plot.",
        media_type: 'movie',
        genre_ids: [878, 16, 28],
    },
    {
        id: 10138,
        poster_path: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
        title: 'Iron Man 2',
        release_date: '2010-04-28',
        vote_average: 6.835,
        vote_count: 19625,
        overview:
            "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances - and confront powerful enemies.",
        media_type: 'movie',
        genre_ids: [12, 28, 878],
    },
    {
        id: 68721,
        poster_path: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
        title: 'Iron Man 3',
        release_date: '2013-04-18',
        vote_average: 6.928,
        vote_count: 20941,
        overview:
            "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
        media_type: 'movie',
        genre_ids: [28, 12, 878],
    },
    {
        id: 41428,
        poster_path: '/lARc59hUAKW3ziWddftUnZ99R8c.jpg',
        title: 'Tetsuo: The Iron Man',
        release_date: '1989-07-01',
        vote_average: 6.942,
        vote_count: 480,
        overview:
            'A "metal fetishist", driven mad by the maggots wriggling in the wound he\'s made to embed metal into his flesh, runs out into the night and is accidentally run down by a Japanese businessman and his girlfriend. The pair dispose of the corpse in hopes of quietly moving on with their lives. However, the businessman soon finds that he is now plagued by a vicious curse that transforms his flesh into iron.',
        media_type: 'movie',
        genre_ids: [27, 878],
    },
    {
        id: 225,
        poster_path: '/22wNUqKyz2m6wzAt31f26H8Y433.jpg',
        title: 'Man of Iron',
        release_date: '1981-07-27',
        vote_average: 6.8,
        vote_count: 59,
        overview:
            'In Warsaw in 1980, the Communist Party sends Winkel, a weak, alcoholic TV hack, to Gdansk to dig up dirt on the shipyard strikers, particularly on Maciek Tomczyk, an articulate worker whose father was killed in the December 1970 protests. Posing as sympathetic, Winkel interviews the people surrounding Tomczyk, including his detained wife, Agnieszka.',
        media_type: 'movie',
        genre_ids: [18, 36],
    },
    {
        id: 13647,
        poster_path: '/eebNTSRa5Hh5skPKGdGJIJpo9Ls.jpg',
        title: 'The Invincible Iron Man',
        release_date: '2007-01-23',
        vote_average: 6.116,
        vote_count: 212,
        overview:
            "When a cocky industrialist's efforts to raise an ancient Chinese temple leads him to be seriously wounded and captured by enemy forces, he must use his ideas for a revolutionary power armor in order to fight back as a superhero.",
        media_type: 'movie',
        genre_ids: [28, 12, 16, 14, 878],
    },
    {
        id: 194310,
        poster_path: '/l66ZkItJmi4er0I0mGe4mksjfB.jpg',
        title: 'Iron Man',
        release_date: '1931-04-29',
        vote_average: 4.8,
        vote_count: 9,
        overview:
            'Prizefighter Mason loses his opening fight so wife Rose leaves him for Hollywood. Without her around Mason trains and starts winning. Rose comes back and wants Mason to dump his manager Regan and replace him with her secret lover Lewis.',
        media_type: 'movie',
        genre_ids: [18],
    },
    {
        id: 339259,
        poster_path: '/ZVQfCY2DgCjrm8w2saXvT8Ao3B.jpg',
        title: 'The Man with the Iron Heart',
        release_date: '2017-05-25',
        vote_average: 6.552,
        vote_count: 696,
        overview:
            'With the Third Reich at its peak in 1942, the Czech resistance in London plans the most ambitious military operation of WWII -  Anthropoid. Two young recruits are sent to Prague to assassinate the most ruthless Nazi leader - Reinhardt Heydrich, head of the SS, the Gestapo and the architect of the Final Solution.',
        media_type: 'movie',
        genre_ids: [10752, 28, 36, 53],
    },
    {
        id: 69592,
        poster_path: '/eJh3B7ekyN97e0PXUeumwVdFVP4.jpg',
        title: 'Iron Man',
        release_date: '1951-09-20',
        vote_average: 3.7,
        vote_count: 7,
        overview:
            'In Coaltown, Pennsylvania, miner Coke Mason hopes to better himself, buy a radio store, and marry Rose Warren. His gambler brother George thinks Coke can be more successful as a boxer, knowing that when he fights he\'s consumed with a murderous rage that makes him an "iron man." Seeing dollar signs in Rose\'s eyes, Coke reluctantly agrees, though he\'s fearful of the "killer instinct" that makes him a knockout success in the ring...and brings him the booing hatred of the fans. Will Coke throw off his personal demon before he kills someone?',
        media_type: 'movie',
        genre_ids: [18],
    },
    {
        id: 284274,
        poster_path: '/CX7eRlaxFXiW3UGQBdQUoSVZRi.jpg',
        title: 'Iron Man & Captain America: Heroes United',
        release_date: '2014-07-29',
        vote_average: 6.311,
        vote_count: 122,
        overview:
            'Iron Man and Captain America battle to keep the Red Skull and his triggerman, Taskmaster, from unleashing an army of Hydra Brutes on the world!  Sequel to the film "Iron Man & Hulk: Heroes United" and feature Iron Man teaming up with Captain America, it comes to accompany the live-action film "Captain America: The Winter Soldier".',
        media_type: 'movie',
        genre_ids: [12, 16, 28],
    },
    {
        id: 278256,
        poster_path: '/9LQ4PEInhA4X35sqRbQlC8LAzNZ.jpg',
        title: 'Bartali: The Iron Man',
        release_date: '2006-03-26',
        vote_average: 6.727,
        vote_count: 44,
        overview:
            'TV Miniseries (2 episodes) about life and rivalry of italian bikers Gino Bartali and Fausto Coppi.',
        media_type: 'movie',
        genre_ids: [10770, 18],
    },
    {
        id: 9313,
        poster_path: '/zHE9yRURvA7DyhYtQxkGTfE1Ywi.jpg',
        title: 'The Man in the Iron Mask',
        release_date: '1998-03-12',
        vote_average: 6.619,
        vote_count: 3523,
        overview:
            "Years have passed since the Three Musketeers, Aramis, Athos and Porthos, have fought together with their friend, D'Artagnan. But with the tyrannical King Louis using his power to wreak havoc in the kingdom while his twin brother, Philippe, remains imprisoned, the Musketeers reunite to abduct Louis and replace him with Philippe.",
        media_type: 'movie',
        genre_ids: [12, 28, 18],
    },
    {
        id: 88642,
        poster_path: '/852WJpqDlKqjXphgjjBL9nvF8wx.jpg',
        title: 'The Iron Super Man',
        release_date: '1975-07-19',
        vote_average: 5.2,
        vote_count: 20,
        overview:
            'An Earth Defence Brigade is formed to protect the world against invaders from outer space. The ruthless Frang Gang begins its raid against the earth on land, sea and by air. But they meet their match in the super robots of the Earth Defence Brigade.',
        media_type: 'movie',
        genre_ids: [28, 35, 14, 878],
    },
    {
        id: 92679,
        poster_path: '/olnMdMunyQzZdizsH8hlAObhTJk.jpg',
        title: 'Man of Iron',
        release_date: '1972-10-13',
        vote_average: 6.3,
        vote_count: 6,
        overview:
            "Man of Iron was positioned as something of a follow-up to Boxer From Shantung, the rise-and-fall story of Ma Yung Chen and it reunites the directors and some of the cast in a similar but much slighter tale of a lesser gangster's rise and fall in Shanghai. While the opening narration specifically recalls the events and tragic conclusion of BOXER, this one is set 20 years later in the same section of Shanghai but otherwise has nothing to do with the events or characters of the previous film.",
        media_type: 'movie',
        genre_ids: [28, 18, 80],
    },
    {
        id: 230896,
        poster_path: '/e7F2ZNA7wMneoSKGonLKjDmjFEd.jpg',
        title: 'Iron Man & Hulk: Heroes United',
        release_date: '2013-12-03',
        vote_average: 5.699,
        vote_count: 166,
        overview:
            "The Invincible Iron Man and the Incredible Hulk must join forces to save the Earth from its greatest threat yet! When two Hydra scientists try to supercharge a Stark Arc Reactor with Hulk's Gamma Energy, they unleash a being of pure electricity called Zzzax - and he's hungry for destruction. Together, Iron Man and Hulk are the only force that stands in the way of the Zzzax's planetary blackout. But first, the super heroic duo will have to get through snarling Wendigos, deadly robots and the scaly powerhouse, Abomination.  Can two of Marvel's mightiest heroes find a way to work together without smashing each other before time runs out?",
        media_type: 'movie',
        genre_ids: [28, 12, 16, 10751],
    },
    {
        id: 928743,
        poster_path: '/cv1C3Bpvb2zUaO1deWosihfmgHV.jpg',
        title: 'The Iron Man',
        release_date: '1973-01-19',
        vote_average: 0,
        vote_count: 0,
        overview:
            "In 1944 Chang Chin's father was murdered by the Japanese with the help of Ching Tang and Fan Hsi-Shang, two collaborators led by Fung Mu. Now a grown up and a master of kung fu, Chang is ready to revenge his father.",
        media_type: 'movie',
        genre_ids: [28],
    },
    {
        id: 1099106,
        poster_path: '/tNC4pNyyny56KECEcNwUdBSTnvw.jpg',
        title: 'Spider-Man, Iron Man and the Hulk',
        release_date: '2007-01-01',
        vote_average: 7.333,
        vote_count: 3,
        overview: 'A small animated movie from Marvel and IIRC Blur Studios.',
        media_type: 'movie',
        genre_ids: [28, 12, 16],
    },
    {
        id: 97430,
        poster_path: '/9dipO9811zpe3P7H26w9X1z1U2y.jpg',
        title: 'The Man with the Iron Fists',
        release_date: '2012-11-02',
        vote_average: 5.512,
        vote_count: 1038,
        overview:
            'In feudal China, a blacksmith who makes weapons for a small village is put in the position where he must defend himself and his fellow villagers.',
        media_type: 'movie',
        genre_ids: [28],
    },
    {
        id: 321494,
        poster_path: '/n1U7x2OMsyI28auLY3U9XB3udl7.jpg',
        title: 'The Man with the Iron Fists 2',
        release_date: '2015-03-10',
        vote_average: 5.5,
        vote_count: 228,
        overview:
            'When a stranger, Thaddeus, is found badly wounded near the village, miner Li Kung and his wife Ah Ni offer him refuge. As he heals, he becomes entrenched in a conflict that pits the townsfolk against the evil Master Ho, his nefarious Beetle Clan and the terrifying Lord Pi.',
        media_type: 'movie',
        genre_ids: [28],
    },
    {
        id: 3097,
        poster_path: '/nTQWWH6CFtl37x1nPx8HRwbwvGn.jpg',
        title: 'Iron Man',
        release_date: '1994-09-24',
        seasons: [fakeSeason, fakeSeason],
        vote_average: 6.702,
        vote_count: 85,
        overview:
            'Industrialist Tony Stark leads a private team of superheroes as Iron Man against the forces of evil.',
        media_type: 'tv',
        genre_ids: [16, 10759, 10765],
    },
    {
        id: 45418,
        poster_path: '/zOTJT7JbzSrMBX2OCGPqUnkQA4y.jpg',
        title: 'Iron Man',
        release_date: '2010-10-01',
        seasons: [fakeSeason, fakeSeason, fakeSeason, fakeSeason],
        vote_average: 7.211,
        vote_count: 76,
        overview:
            "When Tony Stark branches his company into Japan, he is opposed by the nefarious Zodiac organization. It's up to Stark's Iron Man to defeat the Zodiac, and defend Japan.",
        media_type: 'tv',
        genre_ids: [16, 10759, 10765],
    },
    {
        id: 7330,
        poster_path: '/uwMIL8PR1jHpHQksIq7kzdeqg2A.jpg',
        title: 'Iron Man: Armored Adventures',
        release_date: '2009-04-24',
        vote_average: 7.461,
        vote_count: 115,
        overview:
            'Iron Man: Armored Adventures is a 3D CGI cartoon series based on the Marvel Comics superhero Iron Man. It debuted in the USA on the Nicktoons on April 24, 2009, and has already begun airing on Canadian network Teletoon. Iron Man: Armored Adventures aired on Nickelodeon on July 4, 2009 until September 12, 2009. The series is story edited by showrunner Christopher Yost, who also worked on Wolverine and the X-Men, and numerous other Marvel Animation projects. The television show is not related to the 2007 animated film The Invincible Iron Man; It has a different voice cast, but some story elements are similar and the show uses the same musical score as the film in some instances. It is the first Iron Man television series since Iron Man from 1994–1996, and started airing after the success of the live action Iron Man film.\n\nThe series follows the adventures of teenage child prodigy Tony Stark and his alter ego of Iron Man. As Iron Man, he uses his technological inventions to fight various similarly technologically advanced threats. His friends, James "Rhodey" Rhodes and Pepper Potts help him on his courageous, and dangerous adventures.',
        media_type: 'tv',
        genre_ids: [16, 10759, 10765],
    },
    {
        id: 77362,
        poster_path: '/w10ClxT6uqnyxJZiMAx2ty9GkWu.jpg',
        title: 'Iron Man: Extremis',
        release_date: '2010-11-30',
        vote_average: 6.3,
        vote_count: 12,
        overview:
            "An experimental serum called Extremis gets stolen, and Iron Man rockets into action. The ensuing battles test Stark's spirit and Iron Man's power.",
        media_type: 'tv',
        genre_ids: [16],
    },
    {
        id: 18189,
        poster_path: null,
        title: 'Faujji...The Iron Man',
        release_date: '',
        vote_average: 0,
        vote_count: 0,
        overview:
            'Faujji...The Iron Man is a Hindi language Indian television series that airs on the national channel, DD National. The series premiered on March 21, 2009, and airs every Saturday and Sunday at 8:30 pm IST. The story is about the army battling terrorism. On its first day, the series received a Television Rating Point of 1.7 among other shows on other general entertainment channels.',
        media_type: 'tv',
        genre_ids: [10759, 18],
    },
    {
        id: 61739,
        poster_path: '/pRt6yU9zAJfzc9VhARcmn8tIFNl.jpg',
        title: 'Blade Man',
        release_date: '2014-09-10',
        vote_average: 5.6,
        vote_count: 10,
        overview:
            "Despite his wealth, Joo Hong Bin (Lee Dong Wook) is a prickly man harboring a broken heart. But when his emotional pain physically manifests itself as a gruesome ability to sprout knives from his body, Hong Bin quickly realizes that he’s got to start wearing his heart on his sleeve — with all of his newfound scars to prove it. Meanwhile, Son Se Dong (Shin Se Kyung) tries to heal Hong Bin's wounds inside and out, but is this supernatural love damaged beyond repair?",
        media_type: 'tv',
        genre_ids: [18, 10765],
    },
    {
        id: 6153,
        poster_path: '/c0JLcw2vwmBGPsPTlzYerydAAQm.jpg',
        title: 'Gigantor',
        release_date: '1963-10-20',
        vote_average: 6.7,
        vote_count: 3,
        overview:
            'Gigantor is an American adaptation of the anime version of Tetsujin 28-go, a manga by Mitsuteru Yokoyama released in 1956. It debuted on U.S. television in 1964. As with Speed Racer, the characters\' original names were altered and the original series\' violence was toned down for American viewers. The series "was resurrected, in color, as The New Adventures of Gigantor, by the Sci Fi Channel in 1993."',
        media_type: 'tv',
        genre_ids: [16, 10765],
    },
    {
        id: 2164,
        poster_path: '/sUcupSGQRxDfQxr3tcb4KodOXmm.jpg',
        title: 'The Marvel Super Heroes',
        release_date: '1966-09-05',
        vote_average: 8.4,
        vote_count: 5,
        overview:
            'This cartoon series, characterized by extremely limited animation, features five of the most popular super-powered heroes from Marvel Comics: the Incredible Hulk, the Mighty Thor, Captain America, Iron Man, and the Sub-Mariner.',
        media_type: 'tv',
        genre_ids: [16, 10759, 10765, 10762],
    },
    {
        id: 34391,
        poster_path: '/ye6H7F8kKTd3betEfyGpuVD549a.jpg',
        title: "Marvel's Ultimate Spider-Man",
        release_date: '2012-04-01',
        vote_average: 7.669,
        vote_count: 919,
        overview:
            'While being trained by S.H.I.E.L.D., Spider-Man battles evil with a new team of teen colleagues.',
        media_type: 'tv',
        genre_ids: [10762, 10759, 16, 35],
    },
    {
        id: 75189,
        poster_path: '/cPZjDzyDVrqsQzBDoRBLoAAL7iw.jpg',
        title: 'Commandments',
        release_date: '2017-10-17',
        vote_average: 10,
        vote_count: 2,
        overview:
            'The story, which deals with the ultra-Orthodox who enlist in combat training in the Israel Defense Forces, is presented through the eyes of three soldiers: Amram Elkayam the shabbanik, the national ultra-Orthodox Gur Aryeh and Yaakov Anielbitsh, a Vizhnitz Hasid, and soon they discover a world they did not know , To communicate with women in a regular framework, and in some cases, of course, to deal with the hostile attitude toward them in the places they came from, including Yehuda Barkan, Danny Steg and Yishai Golan.',
        media_type: 'tv',
        genre_ids: [18],
    },
    {
        id: 44307,
        poster_path: '/ukS6Z66fFqS1DXsjq7D9282P5Th.jpg',
        title: 'Tetsujin 28-go FX',
        release_date: '1982-10-03',
        vote_average: 0,
        vote_count: 0,
        overview: '',
        media_type: 'tv',
        genre_ids: [16],
    },
];

export const SEASONS_VALID: Season[] = [
    {
        air_date: '2013-12-02',
        episode_count: 11,
        id: 60059,
        name: 'Season 1',
        overview:
            'Rick and Morty visit a pawn shop in space, encounter various alternate and virtual realities, and meet the devil at his antique shop.',
        poster_path: '/h9RUEsA6BROWcg0QF6ngNPX5FFh.jpg',
        season_number: 1,
        vote_average: 8,
    },
    {
        air_date: '2015-07-26',
        episode_count: 10,
        id: 66738,
        name: 'Season 2',
        overview:
            'After Rick and Morty decided to unfreeze time, they must deal with alien parasites, alternate Jerrys and a decaying, possibly non-existent dimension.',
        poster_path: '/zkhGdE29umuKwa6u6mm7e4cXvYY.jpg',
        season_number: 2,
        vote_average: 8.3,
    },
    {
        air_date: '2017-04-01',
        episode_count: 10,
        id: 86926,
        name: 'Season 3',
        overview:
            'Rick and Morty travel to Atlantis and take some time to relax, plus Rick turns himself into a pickle and faces off against the president.',
        poster_path: '/7kP0ykqRPyY5anbCOMlR1PtLj8Y.jpg',
        season_number: 3,
        vote_average: 8.2,
    },
    {
        air_date: '2019-11-10',
        episode_count: 10,
        id: 128112,
        name: 'Season 4',
        overview:
            'Everything and nothing makes sense when bizarre genius Rick and his grandson Morty take more interdimensional journeys that bend time and space.',
        poster_path: '/87abbwoOfm5MMCWoFewN8pNGZxW.jpg',
        season_number: 4,
        vote_average: 7.8,
    },
    {
        air_date: '2021-06-20',
        episode_count: 10,
        id: 188470,
        name: 'Season 5',
        overview:
            'Hold onto your butts — it’s season five, baby! Rick, Morty and the fam are back with ten all-new episodes that consume unheld butts. Sex, romance, testicle monsters… a guy named Mr. Nimbus… It’s everything you want, get your butt ready!',
        poster_path: '/8KdHdOAP8mM4TmykkXnpr6qkyUU.jpg',
        season_number: 5,
        vote_average: 7.2,
    },
    {
        air_date: '2022-09-04',
        episode_count: 10,
        id: 302503,
        name: 'Season 6',
        overview:
            'It’s season six and Rick and Morty are back! Pick up where we left them, worse for wear and down on their luck. Will they manage to bounce back for more adventures? Or will they get swept up in an ocean of piss! Who knows?! Piss! Family! Intrigue! A bunch of dinosaurs! More piss! Another can’t miss season of your favorite show.',
        poster_path: '/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
        season_number: 6,
        vote_average: 7.5,
    },
    {
        air_date: '2023-10-15',
        episode_count: 10,
        id: 354041,
        name: 'Season 7',
        overview:
            "Rick and Morty are back and sounding more like themselves than ever! It's season seven, and the possibilities are endless: what's up with Jerry? EVIL Summer?! And will they ever go back to the high school?! Maybe not! But let's find out! There's probably less piss than last season. \"Rick and Morty,\" 100 years! Or at least until season 10!",
        poster_path: '/OXy96OFiLDZIz9jT4Byxk1Hk6b.jpg',
        season_number: 7,
        vote_average: 7.3,
    },
];

export const SEASONS_INVALID: Season[] = [
    {
        air_date: '2016-10-25',
        episode_count: 35,
        id: 106178,
        name: 'Specials',
        overview: '',
        poster_path: '/3my0MrOKCSYMw8VfLiiM9k00bdF.jpg',
        season_number: 0,
        vote_average: 0,
    },
    {
        air_date: null,
        episode_count: 0,
        id: 424080,
        name: 'Season 8',
        overview: '',
        poster_path: null,
        season_number: 8,
        vote_average: 0,
    },
];
