export enum MOVIE_RATINGS {
    'G',
    'PG',
    'PG-13',
    'R',
}

// https://developer.themoviedb.org/reference/genre-tv-list
// https://developer.themoviedb.org/reference/genre-movie-list
export enum GENRE_IDS {
    Action = 28, // movie only
    Adventure = 12, // movie only
    ActionAdventure = 10759, // tv only
    Animation = 16,
    Comedy = 35,
    Crime = 80,
    Documentary = 99,
    Drama = 18,
    Family = 10751,
    Kids = 10762, // tv only
    Fantasy = 14, // movie only
    History = 36, // movie only
    Horror = 27, // movie only
    Music = 10402, // movie only
    Mystery = 9648,
    News = 10763, // tv only
    Reality = 10764, // tv only
    Romance = 10749, // movie only
    SciFi = 878, // movie only
    SciFiFantasy = 10765, // tv only
    Soap = 10766, // tv only
    Talk = 10767, // tv only
    TvMovie = 10770, // movie only
    Thriller = 53, // movie only
    War = 10752, // movie only
    WarPolitics = 10768, // tv only
    Western = 37,
}

export const PROVIDER_IDS = [
    { provider_name: 'Netflix', provider_id: '8' },
    { provider_name: 'Amazon Prime Video', provider_id: '9' },
    { provider_name: 'Max Amazon Channel', provider_id: '1825' },
    { provider_name: 'Disney Plus', provider_id: '337' },
    { provider_name: 'Apple TV Plus', provider_id: '350' },
    { provider_name: 'Apple TV', provider_id: '2' },
    { provider_name: 'fuboTV', provider_id: '257' },
    { provider_name: 'Hulu', provider_id: '15' },
    { provider_name: 'HBO Max', provider_id: '384' },
    { provider_name: 'Max', provider_id: '1899' },
    { provider_name: 'Crunchyroll', provider_id: '283' },
    { provider_name: 'MGM Plus Amazon Channel', provider_id: '583' },
    { provider_name: 'Peacock', provider_id: '386' },
    { provider_name: 'Peacock Premium', provider_id: '387' },
    { provider_name: 'Kocowa', provider_id: '464' },
    { provider_name: 'Amazon Video', provider_id: '10' },
    { provider_name: 'Google Play Movies', provider_id: '3' },
    { provider_name: 'YouTube', provider_id: '192' },
    { provider_name: 'Paramount Plus', provider_id: '531' },
    { provider_name: 'Paramount+ with Showtime', provider_id: '1770' },
    { provider_name: 'Showtime Apple TV Channel', provider_id: '675' },
    { provider_name: 'Paramount Plus Apple TV Channel ', provider_id: '1853' },
    { provider_name: 'Starz Apple TV Channel', provider_id: '1855' },
    { provider_name: 'AMC Plus Apple TV Channel ', provider_id: '1854' },
    { provider_name: 'Britbox Apple TV Channel ', provider_id: '1852' },
    { provider_name: 'Paramount+ Amazon Channel', provider_id: '582' },
    { provider_name: 'Discovery+ Amazon Channel', provider_id: '584' },
    { provider_name: 'AMC+ Amazon Channel', provider_id: '528' },
    { provider_name: 'Funimation Now', provider_id: '269' },
    { provider_name: 'The Roku Channel', provider_id: '207' },
    { provider_name: 'Showtime Roku Premium Channel', provider_id: '632' },
    { provider_name: 'Paramount+ Roku Premium Channel', provider_id: '633' },
    { provider_name: 'Starz Roku Premium Channel', provider_id: '634' },
    { provider_name: 'AMC+ Roku Premium Channel', provider_id: '635' },
    { provider_name: 'Showtime Amazon Channel', provider_id: '203' },
    { provider_name: 'AMC+', provider_id: '526' },
    { provider_name: 'MGM Plus Roku Premium Channel', provider_id: '636' },
    { provider_name: 'YouTube Premium', provider_id: '188' },
    { provider_name: 'YouTube Free', provider_id: '235' },
    { provider_name: 'The CW', provider_id: '83' },
    { provider_name: 'Hoopla', provider_id: '212' },
    { provider_name: 'Vudu', provider_id: '7' },
    { provider_name: 'Starz', provider_id: '43' },
    { provider_name: 'VUDU Free', provider_id: '332' },
    { provider_name: 'Showtime', provider_id: '37' },
    { provider_name: 'Criterion Channel', provider_id: '258' },
    { provider_name: 'PBS', provider_id: '209' },
    { provider_name: 'Pantaflix', provider_id: '177' },
    { provider_name: 'FXNow', provider_id: '123' },
    { provider_name: 'Tubi TV', provider_id: '73' },
    { provider_name: 'Kanopy', provider_id: '191' },
    { provider_name: 'Comedy Central', provider_id: '243' },
    { provider_name: 'Microsoft Store', provider_id: '68' },
    { provider_name: 'Redbox', provider_id: '279' },
    { provider_name: 'Sun Nxt', provider_id: '309' },
    { provider_name: 'ABC', provider_id: '148' },
    { provider_name: 'Crackle', provider_id: '12' },
    { provider_name: 'DIRECTV', provider_id: '358' },
    { provider_name: 'AMC', provider_id: '80' },
    { provider_name: 'Fandor', provider_id: '25' },
    { provider_name: 'Curiosity Stream', provider_id: '190' },
    { provider_name: 'MGM Plus', provider_id: '34' },
    { provider_name: 'Freeform', provider_id: '211' },
    { provider_name: 'History', provider_id: '155' },
    { provider_name: 'Syfy', provider_id: '215' },
    { provider_name: 'Lifetime', provider_id: '157' },
    { provider_name: 'realeyz', provider_id: '14' },
    { provider_name: 'Shudder', provider_id: '99' },
    { provider_name: 'Acorn TV', provider_id: '87' },
    { provider_name: 'Screambox', provider_id: '185' },
    { provider_name: 'Sundance Now', provider_id: '143' },
    { provider_name: 'Popcornflix', provider_id: '241' },
    { provider_name: 'GuideDoc', provider_id: '100' },
    { provider_name: 'BritBox', provider_id: '151' },
    { provider_name: 'MUBI', provider_id: '11' },
    { provider_name: 'Netflix Kids', provider_id: '175' },
    { provider_name: 'Pantaya', provider_id: '247' },
    { provider_name: 'Boomerang', provider_id: '248' },
    { provider_name: 'Urban Movie Channel', provider_id: '251' },
    { provider_name: 'Dove Channel', provider_id: '254' },
    { provider_name: 'History Vault', provider_id: '268' },
    { provider_name: 'Eros Now', provider_id: '218' },
    { provider_name: 'Nickhits Amazon Channel', provider_id: '261' },
    { provider_name: 'Yupp TV', provider_id: '255' },
    { provider_name: 'Magnolia Selects', provider_id: '259' },
    { provider_name: 'WWE Network', provider_id: '260' },
    { provider_name: 'Noggin Amazon Channel', provider_id: '262' },
    { provider_name: 'Smithsonian Channel', provider_id: '276' },
    { provider_name: 'Laugh Out Loud', provider_id: '275' },
    { provider_name: 'Hallmark Movies', provider_id: '281' },
    { provider_name: 'Pure Flix', provider_id: '278' },
    { provider_name: 'Lifetime Movie Club', provider_id: '284' },
    { provider_name: 'PBS Kids Amazon Channel', provider_id: '293' },
    { provider_name: 'Boomerang Amazon Channel', provider_id: '288' },
    { provider_name: 'Cinemax Amazon Channel', provider_id: '289' },
    { provider_name: 'Hallmark Movies Now Amazon Channel', provider_id: '290' },
    { provider_name: 'PBS Masterpiece Amazon Channel', provider_id: '294' },
    { provider_name: 'Viewster Amazon Channel', provider_id: '295' },
    { provider_name: 'MZ Choice Amazon Channel', provider_id: '291' },
    { provider_name: 'Spamflix', provider_id: '521' },
    { provider_name: 'Pluto TV', provider_id: '300' },
    { provider_name: 'HiDive', provider_id: '430' },
    { provider_name: 'VIX ', provider_id: '457' },
    { provider_name: 'Night Flight Plus', provider_id: '455' },
    { provider_name: 'Topic', provider_id: '454' },
    { provider_name: 'Retrocrush', provider_id: '446' },
    { provider_name: 'Classix', provider_id: '445' },
    { provider_name: 'Dekkoo', provider_id: '444' },
    { provider_name: 'Shout! Factory TV', provider_id: '439' },
    { provider_name: 'OVID', provider_id: '433' },
    { provider_name: 'Chai Flicks', provider_id: '438' },
    { provider_name: 'The Film Detective', provider_id: '470' },
    { provider_name: 'Shudder Amazon Channel', provider_id: '204' },
    { provider_name: 'MUBI Amazon Channel', provider_id: '201' },
    { provider_name: 'AcornTV Amazon Channel', provider_id: '196' },
    { provider_name: 'BritBox Amazon Channel', provider_id: '197' },
    { provider_name: 'Fandor Amazon Channel', provider_id: '199' },
    { provider_name: 'Screambox Amazon Channel', provider_id: '202' },
    { provider_name: 'USA Network', provider_id: '322' },
    { provider_name: 'Bet+ Amazon Channel', provider_id: '343' },
    { provider_name: 'FlixFling', provider_id: '331' },
    { provider_name: 'Rakuten Viki', provider_id: '344' },
    { provider_name: 'AMC on Demand', provider_id: '352' },
    { provider_name: 'Darkmatter TV', provider_id: '355' },
    { provider_name: 'TCM', provider_id: '361' },
    { provider_name: 'TNT', provider_id: '363' },
    { provider_name: 'BBC America', provider_id: '397' },
    { provider_name: 'IndieFlix', provider_id: '368' },
    { provider_name: 'Here TV', provider_id: '417' },
    { provider_name: 'Flix Premiere', provider_id: '432' },
    { provider_name: 'TBS', provider_id: '506' },
    { provider_name: 'AsianCrush', provider_id: '514' },
    { provider_name: 'FILMRISE', provider_id: '471' },
    { provider_name: 'Revry', provider_id: '473' },
    { provider_name: 'DOCSVILLE', provider_id: '475' },
    { provider_name: 'Spectrum On Demand', provider_id: '486' },
    { provider_name: 'Hi-YAH', provider_id: '503' },
    { provider_name: 'tru TV', provider_id: '507' },
    { provider_name: 'DisneyNOW', provider_id: '508' },
    { provider_name: 'ARROW', provider_id: '529' },
    { provider_name: 'Plex', provider_id: '538' },
    { provider_name: 'WOW Presents Plus', provider_id: '546' },
    { provider_name: 'Magellan TV', provider_id: '551' },
    { provider_name: 'Alamo on Demand', provider_id: '547' },
    { provider_name: 'BroadwayHD', provider_id: '554' },
    { provider_name: 'Filmzie', provider_id: '559' },
    { provider_name: 'Dogwoof On Demand', provider_id: '536' },
    { provider_name: 'MovieSaints', provider_id: '562' },
    { provider_name: 'True Story', provider_id: '567' },
    { provider_name: 'DocAlliance Films', provider_id: '569' },
    { provider_name: 'KoreaOnDemand', provider_id: '575' },
    { provider_name: 'Hoichoi', provider_id: '315' },
    { provider_name: 'Film Movement Plus', provider_id: '579' },
    { provider_name: 'iQIYI', provider_id: '581' },
    { provider_name: 'Metrograph', provider_id: '585' },
    { provider_name: 'Freevee', provider_id: '613' },
    { provider_name: 'Public Domain Movies', provider_id: '638' },
    { provider_name: 'Kino Now', provider_id: '640' },
    { provider_name: 'Eventive', provider_id: '677' },
    { provider_name: 'Cultpix', provider_id: '692' },
    { provider_name: 'aha', provider_id: '532' },
    { provider_name: 'FilmBox+', provider_id: '701' },
    { provider_name: 'ShortsTV Amazon Channel', provider_id: '688' },
    { provider_name: 'Bet+', provider_id: '1759' },
    { provider_name: 'Takflix', provider_id: '1771' },
    { provider_name: 'Klassiki', provider_id: '1793' },
    { provider_name: 'Starz Amazon Channel', provider_id: '1794' },
    { provider_name: 'Netflix basic with Ads', provider_id: '1796' },
    { provider_name: 'Cohen Media Amazon Channel', provider_id: '1811' },
    { provider_name: 'Popflick', provider_id: '1832' },
    { provider_name: 'Viaplay', provider_id: '76' },
    { provider_name: 'Runtime', provider_id: '1875' },
];

export const COUNTRIES = [
    { country: 'Andorra', abbrev: 'AD' },
    { country: 'United Arab Emirates', abbrev: 'AE' },
    { country: 'Antigua and Barbuda', abbrev: 'AG' },
    { country: 'Albania', abbrev: 'AL' },
    { country: 'Angola', abbrev: 'AO' },
    { country: 'Argentina', abbrev: 'AR' },
    { country: 'Austria', abbrev: 'AT' },
    { country: 'Australia', abbrev: 'AU' },
    { country: 'Azerbaijan', abbrev: 'AZ' },
    { country: 'Bosnia and Herzegovina', abbrev: 'BA' },
    { country: 'Barbados', abbrev: 'BB' },
    { country: 'Belgium', abbrev: 'BE' },
    { country: 'Burkina Faso', abbrev: 'BF' },
    { country: 'Bulgaria', abbrev: 'BG' },
    { country: 'Bahrain', abbrev: 'BH' },
    { country: 'Bermuda', abbrev: 'BM' },
    { country: 'Bolivia', abbrev: 'BO' },
    { country: 'Brazil', abbrev: 'BR' },
    { country: 'Bahamas', abbrev: 'BS' },
    { country: 'Belarus', abbrev: 'BY' },
    { country: 'Belize', abbrev: 'BZ' },
    { country: 'Canada', abbrev: 'CA' },
    { country: 'Congo', abbrev: 'CD' },
    { country: 'Switzerland', abbrev: 'CH' },
    // eslint-disable-next-line prettier/prettier
    { country: 'Cote D\'Ivoire', abbrev: 'CI' },
    { country: 'Chile', abbrev: 'CL' },
    { country: 'Cameroon', abbrev: 'CM' },
    { country: 'Colombia', abbrev: 'CO' },
    { country: 'Costa Rica', abbrev: 'CR' },
    { country: 'Cuba', abbrev: 'CU' },
    { country: 'Cape Verde', abbrev: 'CV' },
    { country: 'Cyprus', abbrev: 'CY' },
    { country: 'Czech Republic', abbrev: 'CZ' },
    { country: 'Germany', abbrev: 'DE' },
    { country: 'Denmark', abbrev: 'DK' },
    { country: 'Dominican Republic', abbrev: 'DO' },
    { country: 'Algeria', abbrev: 'DZ' },
    { country: 'Ecuador', abbrev: 'EC' },
    { country: 'Estonia', abbrev: 'EE' },
    { country: 'Egypt', abbrev: 'EG' },
    { country: 'Spain', abbrev: 'ES' },
    { country: 'Finland', abbrev: 'FI' },
    { country: 'Fiji', abbrev: 'FJ' },
    { country: 'France', abbrev: 'FR' },
    { country: 'United Kingdom', abbrev: 'GB' },
    { country: 'French Guiana', abbrev: 'GF' },
    { country: 'Ghana', abbrev: 'GH' },
    { country: 'Gibraltar', abbrev: 'GI' },
    { country: 'Guadaloupe', abbrev: 'GP' },
    { country: 'Equatorial Guinea', abbrev: 'GQ' },
    { country: 'Greece', abbrev: 'GR' },
    { country: 'Guatemala', abbrev: 'GT' },
    { country: 'Guyana', abbrev: 'GY' },
    { country: 'Hong Kong', abbrev: 'HK' },
    { country: 'Honduras', abbrev: 'HN' },
    { country: 'Croatia', abbrev: 'HR' },
    { country: 'Hungary', abbrev: 'HU' },
    { country: 'Indonesia', abbrev: 'ID' },
    { country: 'Ireland', abbrev: 'IE' },
    { country: 'Israel', abbrev: 'IL' },
    { country: 'India', abbrev: 'IN' },
    { country: 'Iraq', abbrev: 'IQ' },
    { country: 'Iceland', abbrev: 'IS' },
    { country: 'Italy', abbrev: 'IT' },
    { country: 'Jamaica', abbrev: 'JM' },
    { country: 'Jordan', abbrev: 'JO' },
    { country: 'Japan', abbrev: 'JP' },
    { country: 'Kenya', abbrev: 'KE' },
    { country: 'South Korea', abbrev: 'KR' },
    { country: 'Kuwait', abbrev: 'KW' },
    { country: 'Lebanon', abbrev: 'LB' },
    { country: 'St. Lucia', abbrev: 'LC' },
    { country: 'Liechtenstein', abbrev: 'LI' },
    { country: 'Lithuania', abbrev: 'LT' },
    { country: 'Luxembourg', abbrev: 'LU' },
    { country: 'Latvia', abbrev: 'LV' },
    { country: 'Libyan Arab Jamahiriya', abbrev: 'LY' },
    { country: 'Morocco', abbrev: 'MA' },
    { country: 'Monaco', abbrev: 'MC' },
    { country: 'Moldova', abbrev: 'MD' },
    { country: 'Montenegro', abbrev: 'ME' },
    { country: 'Madagascar', abbrev: 'MG' },
    { country: 'Macedonia', abbrev: 'MK' },
    { country: 'Mali', abbrev: 'ML' },
    { country: 'Malta', abbrev: 'MT' },
    { country: 'Mauritius', abbrev: 'MU' },
    { country: 'Malawi', abbrev: 'MW' },
    { country: 'Mexico', abbrev: 'MX' },
    { country: 'Malaysia', abbrev: 'MY' },
    { country: 'Mozambique', abbrev: 'MZ' },
    { country: 'Niger', abbrev: 'NE' },
    { country: 'Nigeria', abbrev: 'NG' },
    { country: 'Nicaragua', abbrev: 'NI' },
    { country: 'Netherlands', abbrev: 'NL' },
    { country: 'Norway', abbrev: 'NO' },
    { country: 'New Zealand', abbrev: 'NZ' },
    { country: 'Oman', abbrev: 'OM' },
    { country: 'Panama', abbrev: 'PA' },
    { country: 'Peru', abbrev: 'PE' },
    { country: 'French Polynesia', abbrev: 'PF' },
    { country: 'Papua New Guinea', abbrev: 'PG' },
    { country: 'Philippines', abbrev: 'PH' },
    { country: 'Pakistan', abbrev: 'PK' },
    { country: 'Poland', abbrev: 'PL' },
    { country: 'Palestinian Territory', abbrev: 'PS' },
    { country: 'Portugal', abbrev: 'PT' },
    { country: 'Paraguay', abbrev: 'PY' },
    { country: 'Qatar', abbrev: 'QA' },
    { country: 'Romania', abbrev: 'RO' },
    { country: 'Serbia', abbrev: 'RS' },
    { country: 'Russia', abbrev: 'RU' },
    { country: 'Saudi Arabia', abbrev: 'SA' },
    { country: 'Seychelles', abbrev: 'SC' },
    { country: 'Sweden', abbrev: 'SE' },
    { country: 'Singapore', abbrev: 'SG' },
    { country: 'Slovenia', abbrev: 'SI' },
    { country: 'Slovakia', abbrev: 'SK' },
    { country: 'San Marino', abbrev: 'SM' },
    { country: 'Senegal', abbrev: 'SN' },
    { country: 'El Salvador', abbrev: 'SV' },
    { country: 'Turks and Caicos Islands', abbrev: 'TC' },
    { country: 'Chad', abbrev: 'TD' },
    { country: 'Thailand', abbrev: 'TH' },
    { country: 'Tunisia', abbrev: 'TN' },
    { country: 'Turkey', abbrev: 'TR' },
    { country: 'Trinidad and Tobago', abbrev: 'TT' },
    { country: 'Taiwan', abbrev: 'TW' },
    { country: 'Tanzania', abbrev: 'TZ' },
    { country: 'Ukraine', abbrev: 'UA' },
    { country: 'Uganda', abbrev: 'UG' },
    { country: 'United States of America', abbrev: 'US' },
    { country: 'Uruguay', abbrev: 'UY' },
    { country: 'Holy See', abbrev: 'VA' },
    { country: 'Venezuela', abbrev: 'VE' },
    { country: 'Kosovo', abbrev: 'XK' },
    { country: 'Yemen', abbrev: 'YE' },
    { country: 'South Africa', abbrev: 'ZA' },
    { country: 'Zambia', abbrev: 'ZM' },
    { country: 'Zimbabwe', abbrev: 'ZW' },
];
