name: CI
on: 
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  
jobs:
  build:
    name: Streamability CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install modules
      run: |
        npm ci
        npm run patch
    - name: Run typescript compiler
      run: npm run compile
    - name: Run ESLint
      run: |
        npx eslint . --ext .ts,.tsx
        npx markdownlint *.md **/*.md .github/*.md --ignore node_modules
    - name: Run todo report
      run: |
        npm run todo-pr
        git diff --no-index --exit-code TODO.md PR_TODO.md
    - name: Create .env
      run: |
        touch .env
        echo VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
        echo VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_KEY }} >> .env
        echo VITE_MOVIEDB_KEY=${{ secrets.MOVIEDB_KEY }} >> .env
        cat .env
    - name: Run unit tests
      run: npm run test
